import type { Metadata } from "next";
import "./globals.css";
import { kalam, kalamBold, yuyu } from "@/libs/fonts";

export const metadata: Metadata = {
  title: "Scratched",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${kalam.variable} ${kalamBold.variable} ${yuyu.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
