import type { Metadata } from "next";
import "./globals.css";
import { kalam, kalamBold, yuyu } from "@/libs/fonts";
import ConvexClientProvider from "@/providers/ConvexProvides";
import Script from "next/script";
import AfterwordNavbar from "@/components/major/NavBar";
import React from "react";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Scratched",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kalam.variable} ${kalamBold.variable} ${yuyu.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Analytics />
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
